### ISSUE TITLE
建议及时更新文档，避免产生Error: Error: Input required and not supplied: server

### ISSUE THREAD

**Issue by Oshibuki** [rockbenben/LearnData#15]
文档中没有提到在初次运行action时需要删除以下代码，卡了半天
```
      ### 没有服务器的话，请删除本区块代码，防止报错 ###
      # 将页面推送到服务器，timeout 时间从默认的 1 分钟调整到 10 分钟。
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          local-dir: docs/.vuepress/dist/
          server: ${{ secrets.ftp_host }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          port: ${{ secrets.ftp_port }} # 建议更改默认的 21 端口
          timeout: 600000
      ### 没有服务器的话，请删除本区块代码，防止报错 ###
```
